services:
  # Frontend Service
  - type: static
    name: kundflow-frontend
    buildCommand: |
      ls -la
      pwd
      npm --prefix frontend install
      npm --prefix frontend run build
    publishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
        - frontend/**

  # Backend Service
  - type: web
    name: kundflow-backend
    env: node
    buildCommand: |
      ls -la
      pwd
      npm --prefix backend install
      npm --prefix backend run build
    startCommand: npm --prefix backend run start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: eu-north-1
      - key: AWS_S3_BUCKET
        value: kundflow-contracts
      - key: AWS_TEXTRACT_BUCKET
        value: kundflow-textract
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /api/health
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
