services:
  # Frontend Service
  - type: static
    name: kundflow-frontend
    buildCommand: |
      npm install -g npm@latest
      chmod +x deploy.sh
      ./deploy.sh
    publishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: VITE_API_URL
        value: https://kundflow-backend.onrender.com
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
        - frontend/**

  # Backend Service
  - type: web
    name: kundflow-backend
    env: node
    buildCommand: |
      npm install -g npm@latest
      cd backend
      npm ci
      npm run build
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: eu-north-1
      - key: AWS_S3_BUCKET
        value: kundflow-contracts
      - key: AWS_TEXTRACT_BUCKET
        value: kundflow-textract
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://kundflow-frontend.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
