name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kundflow_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    # Backend
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci --legacy-peer-deps
      
    - name: Generate Prisma Client
      run: |
        cd backend
        npx prisma generate
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/kundflow_test

    - name: Run Backend Tests
      run: |
        cd backend
        npm run test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/kundflow_test
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1
        AWS_S3_BUCKET: kundflow-contracts-test
        AWS_TEXTRACT_BUCKET: kundflow-textract-test
        NODE_ENV: test

    - name: Build Backend
      run: |
        cd backend
        npm run build

    # Frontend
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci --legacy-peer-deps

    - name: Run Frontend Type Check
      run: |
        cd frontend
        npm run type-check

    - name: Run Frontend Tests
      run: |
        cd frontend
        npm run test
      env:
        VITE_API_URL: https://kundflow-backend.onrender.com

    - name: Build Frontend
      run: |
        cd frontend
        npm run build
      env:
        VITE_API_URL: https://kundflow-backend.onrender.com
